import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://slxadmotlehyyawoayxh.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNseGFkbW90bGVoeXlhd29heXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTY1NDAsImV4cCI6MjA1OTIzMjU0MH0.SoOdNTyYio12PTbLKAS0wP1OWJNNlY5FyadUsXi_YOY';

export const supabase = createClient('https://slxadmotlehyyawoayxh.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNseGFkbW90bGVoeXlhd29heXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTY1NDAsImV4cCI6MjA1OTIzMjU0MH0.SoOdNTyYio12PTbLKAS0wP1OWJNNlY5FyadUsXi_YOY');